title: Own blog
author: Huho
email: maili
description: > # this means to ignore newlines until "baseurl:"
  Juho's test blog

# social links
twitter_username: na yet
github_username:  na yet

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
